require('dotenv').config();
const mqtt = require('mqtt');
const supabase = require('./db');
const { setMqttClient } = require('./api');
require('./ocpp');
const DEVICE_TOPIC_MAP = { 'EVFLO-01': 'shelly1pmg4-EVFLO-01' };
const TOPIC_DEVICE_MAP = {};
Object.entries(DEVICE_TOPIC_MAP).forEach(([k, v]) => TOPIC_DEVICE_MAP[v] = k);
const client = mqtt.connect('mqtt://localhost:1883', { username: process.env.MQTT_USER, password: process.env.MQTT_PASS });
client.on('connect', () => { console.log('[EVFLO] Connected to MQTT'); Object.values(DEVICE_TOPIC_MAP).forEach(prefix => { client.subscribe(prefix + '/#', (err) => { if (!err) console.log('[EVFLO] Subscribed to ' + prefix + '/#'); }); }); setMqttClient(client, DEVICE_TOPIC_MAP); });
client.on('message', (topic, message) => { const payload = message.toString(); console.log('[MQTT] ' + topic + ' -> ' + payload); handleShellyMessage(topic, payload); });
client.on('error', (err) => { console.error('[MQTT] Error:', err.message); });
function handleShellyMessage(topic, payload) { const parts = topic.split('/'); const topicPrefix = parts[0]; const deviceId = TOPIC_DEVICE_MAP[topicPrefix]; if (!deviceId) return; const property = parts.slice(1).join('/'); if (property === 'online') { console.log('[DEVICE] ' + deviceId + ' is ' + payload); return; } if (property === 'status/switch:0') { try { const data = JSON.parse(payload); const watts = data.apower != null ? data.apower : null; const kwh = data.aenergy && data.aenergy.total != null ? data.aenergy.total : null; const output = data.output != null ? data.output : null; if (output !== null) console.log('[DEVICE] ' + deviceId + ' relay: ' + (output ? 'ON' : 'OFF')); if (watts !== null) { console.log('[DEVICE] ' + deviceId + ' power: ' + watts + 'W'); checkForFault(deviceId, watts); } if (kwh !== null) { console.log('[DEVICE] ' + deviceId + ' energy: ' + kwh + ' kWh'); storeTelemetry(deviceId, kwh, watts); } } catch(e) { console.error('[MQTT] Parse error:', e.message); } } }
async function storeTelemetry(deviceId, kwhReading, powerWatts) { try { const { data: cp } = await supabase.from('charge_points').select('id').eq('device_id', deviceId).single(); if (!cp) return; const { data: session } = await supabase.from('sessions').select('id').eq('charge_point_id', cp.id).eq('status', 'active').single(); if (!session) return; await supabase.from('session_telemetry').insert({ session_id: session.id, kwh_total: kwhReading, watts: powerWatts, timestamp: new Date().toISOString() }); } catch(err) { console.error('[TELEMETRY] Error:', err.message); } }
const activeSessions = {};
function checkForFault(deviceId, watts) { if (!activeSessions[deviceId]) return; const session = activeSessions[deviceId]; if (watts === 0) { if (!session.faultStart) { session.faultStart = Date.now(); console.log('[FAULT] ' + deviceId + ' power 0W - monitoring...'); } else { const elapsed = (Date.now() - session.faultStart) / 1000; if (elapsed > 30 && !session.faultFlagged) { session.faultFlagged = true; console.log('[FAULT] ' + deviceId + ' confirmed fault ' + elapsed.toFixed(0) + 's'); } } } else { if (session.faultFlagged) { console.log('[FAULT] ' + deviceId + ' power restored'); session.faultFlagged = false; } session.faultStart = null; } }
function startCharging(deviceId) { const prefix = DEVICE_TOPIC_MAP[deviceId]; if (!prefix) { console.error('[CONTROL] Unknown device: ' + deviceId); return; } client.publish(prefix + '/command/switch:0', 'on'); activeSessions[deviceId] = { startTime: Date.now(), faultStart: null, faultFlagged: false }; console.log('[CONTROL] Started charging on ' + deviceId); }
function stopCharging(deviceId) { const prefix = DEVICE_TOPIC_MAP[deviceId]; if (!prefix) { console.error('[CONTROL] Unknown device: ' + deviceId); return; } client.publish(prefix + '/command/switch:0', 'off'); delete activeSessions[deviceId]; console.log('[CONTROL] Stopped charging on ' + deviceId); }
module.exports = { startCharging, stopCharging };
console.log('[EVFLO] Middleware starting...');
